version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME:-makeup-sdk}-mongo
    restart: unless-stopped
    ports:
      - "${MONGO_PORT:-27020}:27017"  # استفاده از MONGO_PORT شما
    volumes:
      - mongo_data:/data/db
      - ./docker/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
    networks:
      - app-network
    command: mongod --auth

  mongo-express:
    image: mongo-express:latest
    container_name: ${COMPOSE_PROJECT_NAME:-makeup-sdk}-mongo-express
    restart: unless-stopped
    ports:
      - "${MONGO_EXPRESS_PORT:-8085}:8081"  # استفاده از MONGO_EXPRESS_PORT شما
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS:-pass}
    depends_on:
      - mongo
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: ${COMPOSE_PROJECT_NAME:-makeup-sdk}-redis
    restart: unless-stopped
    command: redis-server --protected-mode no
    ports:
      - "${REDIS_PORT:-6380}:6379"  # استفاده از REDIS_PORT شما
    volumes:
      - redis_data:/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME:-makeup-sdk}-api
    restart: unless-stopped
    ports:
      - "4000:${PORT:-4000}"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
  redis_data: